export const PROJECT_NAME_MAX_LENGTH = 100;
export const PROJECT_DESCRIPTION_MAX_LENGTH = 500;
export const PROJECT_POST_TITLE_MAX_LENGTH = 150;
export const PROJECT_POST_CONTENT_MAX_BYTES = 400_000;
