export const BBToHTML: { [key: string]: string } = {
	'[b]': '<b>',
	'[/b]': '</b>',
	'[p]': '<p>',
	'[/p]': '</p>',
	'[i]': '<i>',
	'[/i]': '</i>',
	'[u]': '<u>',
	'[/u]': '</u>',
	'[list]': '<ul>',
	'[/list]': '</ul>',
	'[olist]': '<ol>',
	'[/olist]': '</ol>',
	'[*]': '<li>',
	'[/*]': '</li>',
	'[quote]': '<blockquote>',
	'[/quote]': '</blockquote>',
	'[code]': '<code>',
	'[/code]': '</code>',
	'[hr]': '<hr>',
	'[/hr]': '',
	'[h1]': '<h1>',
	'[/h1]': '</h1>',
	'[h2]': '<h2>',
	'[/h2]': '</h2>',
	'[h3]': '<h3>',
	'[/h3]': '</h3>',
	'[h4]': '<h4>',
	'[/h4]': '</h4>',
	'[h5]': '<h5>',
	'[/h5]': '</h5>',
	'[table]': '<table>',
	'[/table]': '</table>',
	'[td]': '<td>',
	'[/td]': '</td>',
	'[tr]': '<tr>',
	'[/tr]': '</tr>'
};
// export const BBToHTML: Record<string, string> = {
// 	"[h1]": '<h1>',
// 	"[/h1]": '</h1>',
// 	"[h2]": '<h2>',
// 	"[/h2]": '</h2>',
// 	"[h3]": '<h3>',
// 	"[/h3]": '</h3>',
// 	"[b]": '<b>',
// 	"[/b]": '</b>',
// 	"[u]": '<ul>',
// 	"[/u]": '</ul>',
// 	"[i]": '<i>',
// 	"[/i]": '</i>',
// 	"[strike]": '<strike>',
// 	"[/strike]": '</strike>',
// 	"[spoiler]": '<spoiler>',
// 	"[/spoiler]": '</spoiler>',
// 	"[noparse]": '<>',
// 	"[/noparse]": '<>',
// 	"[hr]": '<>',
// 	"[/hr]": '<>',
// 	"[url=": '<a>',
// 	"[/url]": '</a>',
// 	"[img]": '<img src="',
// 	"[/img]": '"</img>',
// 	"[list]": '<ul>',
// 	"[/list]": '</ul>',
// 	"[olist]": '<li>',
// 	"[/olist]": '</li>',
// 	"[*]": '<li>',
// 	"[quote]": '<>',
// 	"[/quote]": '<>',
// 	"[code]": '<>',
// 	"[/code]": '<>',
// }

// export const BBCodeModel = {
// 	Header1Open:"[h1]",
// 	Header1Close:"[/h1]",
// 	Header2Open:"[h2]",
// 	Header2Close:"[/h2]",
// 	Header3Open:"[h3]",
// 	Header3Close:"[/h3]",
// 	BoldOpen:"[b]",
// 	BoldClose:"[/b]",
// 	UnderlineOpen:"[u]",
// 	UnderlineClose:"[/u]",
// 	ItalicOpen:"[i]",
// 	ItalicClose:"[/i]",
// 	StrikethroughOpen:"[strike]",
// 	StrikethroughClose:"[/strike]",
// 	SpoilerOpen:"[spoiler]",
// 	SpoilerClose:"[/spoiler]",
// 	NoParseOpen:"[noparse]",
// 	NoParseClose:"[/noparse]",
// 	HorizontalRuleOpen:"[hr]",
// 	HorizontalRuleClose:"[/hr]",
// 	UrlOpen:"[url=",
// 	UrlClose:"[/url]",
// 	ImageOpen:"[img]",
// 	ImageClose:"[/img]",
// 	ListOpen:"[list]",
// 	ListClose:"[/list]",
// 	OrderedListOpen:"[olist]",
// 	OrderedListClose:"[/olist]",
// 	BulletItem:"[*]",
// 	QuoteOpen:"[quote]",
// 	QuoteClose:"[/quote]",
// 	CodeOpen:"[code]",
// 	CodeClose:"[/code]",
// 	Newline:"\n",
// }
